use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlatformInfo {
    pub id: u64,
    pub name: String,
    pub slug: String,
    pub icon_url: String,
    pub is_active: bool,
}

pub fn get_default_platforms() -> Vec<PlatformInfo> {
    vec![
        PlatformInfo { id: 1, name: "Sega Genesis".to_string(), slug: "Genesis".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/md.png".to_string(), is_active: true },
        PlatformInfo { id: 2, name: "Nintendo 64".to_string(), slug: "N64".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/n64.png".to_string(), is_active: true },
        PlatformInfo { id: 3, name: "Super Nintendo Entertainment System".to_string(), slug: "SNES".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/snes.png".to_string(), is_active: true },
        PlatformInfo { id: 4, name: "Game Boy".to_string(), slug: "GameBoy".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/gb.png".to_string(), is_active: true },
        PlatformInfo { id: 5, name: "Game Boy Advance".to_string(), slug: "GBA".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/gba.png".to_string(), is_active: true },
        PlatformInfo { id: 6, name: "Game Boy Color".to_string(), slug: "GBC".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/gbc.png".to_string(), is_active: true },
        PlatformInfo { id: 7, name: "Nintendo Entertainment System".to_string(), slug: "NES".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/nes.png".to_string(), is_active: true },
        PlatformInfo { id: 8, name: "TurboGrafx-16".to_string(), slug: "PCE".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/pce.png".to_string(), is_active: true },
        PlatformInfo { id: 9, name: "Sega CD".to_string(), slug: "SegaCD".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/scd.png".to_string(), is_active: true },
        PlatformInfo { id: 10, name: "Sega 32X".to_string(), slug: "32X".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/32x.png".to_string(), is_active: true },
        PlatformInfo { id: 11, name: "Sega Master System".to_string(), slug: "MasterSystem".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/sms.png".to_string(), is_active: true },
        PlatformInfo { id: 12, name: "PlayStation".to_string(), slug: "PS1".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/ps1.png".to_string(), is_active: true },
        PlatformInfo { id: 13, name: "Atari Lynx".to_string(), slug: "Lynx".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/lynx.png".to_string(), is_active: true },
        PlatformInfo { id: 14, name: "Neo Geo Pocket".to_string(), slug: "NGP".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/ngp.png".to_string(), is_active: true },
        PlatformInfo { id: 15, name: "Game Gear".to_string(), slug: "GameGear".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/gg.png".to_string(), is_active: true },
        PlatformInfo { id: 16, name: "GameCube".to_string(), slug: "GameCube".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/gc.png".to_string(), is_active: true },
        PlatformInfo { id: 17, name: "Atari Jaguar".to_string(), slug: "Jaguar".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/jag.png".to_string(), is_active: true },
        PlatformInfo { id: 18, name: "Nintendo DS".to_string(), slug: "NDS".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/ds.png".to_string(), is_active: true },
        PlatformInfo { id: 19, name: "Wii".to_string(), slug: "Wii".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/wii.png".to_string(), is_active: true },
        PlatformInfo { id: 20, name: "Wii U".to_string(), slug: "WiiU".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/wiiu.png".to_string(), is_active: false },
        PlatformInfo { id: 21, name: "PlayStation 2".to_string(), slug: "PS2".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/ps2.png".to_string(), is_active: true },
        PlatformInfo { id: 22, name: "Xbox".to_string(), slug: "Xbox".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/xbox.png".to_string(), is_active: false },
        PlatformInfo { id: 23, name: "Magnavox Odyssey 2".to_string(), slug: "Odyssey2".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/mo2.png".to_string(), is_active: true },
        PlatformInfo { id: 24, name: "Pokemon Mini".to_string(), slug: "PokemonMini".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/mini.png".to_string(), is_active: true },
        PlatformInfo { id: 25, name: "Atari 2600".to_string(), slug: "Atari2600".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/2600.png".to_string(), is_active: true },
        PlatformInfo { id: 26, name: "DOS".to_string(), slug: "DOS".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/dos.png".to_string(), is_active: true },
        PlatformInfo { id: 27, name: "Arcade".to_string(), slug: "Arcade".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/arc.png".to_string(), is_active: true },
        PlatformInfo { id: 28, name: "Virtual Boy".to_string(), slug: "VirtualBoy".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/vb.png".to_string(), is_active: true },
        PlatformInfo { id: 29, name: "MSX".to_string(), slug: "MSX".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/msx.png".to_string(), is_active: true },
        PlatformInfo { id: 30, name: "Commodore 64".to_string(), slug: "C64".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/c64.png".to_string(), is_active: true },
        PlatformInfo { id: 31, name: "ZX81".to_string(), slug: "ZX81".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/zx81.png".to_string(), is_active: true },
        PlatformInfo { id: 33, name: "SG-1000".to_string(), slug: "SG1000".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/sg1k.png".to_string(), is_active: true },
        PlatformInfo { id: 37, name: "Amstrad CPC".to_string(), slug: "AmstradCPC".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/cpc.png".to_string(), is_active: true },
        PlatformInfo { id: 38, name: "Apple II".to_string(), slug: "AppleII".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/a2.png".to_string(), is_active: true },
        PlatformInfo { id: 39, name: "Sega Saturn".to_string(), slug: "Saturn".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/sat.png".to_string(), is_active: true },
        PlatformInfo { id: 40, name: "Dreamcast".to_string(), slug: "Dreamcast".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/dc.png".to_string(), is_active: true },
        PlatformInfo { id: 41, name: "PlayStation Portable".to_string(), slug: "PSP".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/psp.png".to_string(), is_active: true },
        PlatformInfo { id: 43, name: "3DO".to_string(), slug: "3DO".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/3do.png".to_string(), is_active: true },
        PlatformInfo { id: 44, name: "ColecoVision".to_string(), slug: "ColecoVision".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/cv.png".to_string(), is_active: true },
        PlatformInfo { id: 45, name: "Intellivision".to_string(), slug: "Intellivision".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/intv.png".to_string(), is_active: true },
        PlatformInfo { id: 46, name: "Vectrex".to_string(), slug: "Vectrex".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/vect.png".to_string(), is_active: true },
        PlatformInfo { id: 49, name: "PC-FX".to_string(), slug: "PCFX".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/pc-fx.png".to_string(), is_active: true },
        PlatformInfo { id: 51, name: "Atari 7800".to_string(), slug: "Atari7800".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/7800.png".to_string(), is_active: true },
        PlatformInfo { id: 53, name: "WonderSwan".to_string(), slug: "WonderSwan".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/ws.png".to_string(), is_active: true },
        PlatformInfo { id: 56, name: "Neo Geo CD".to_string(), slug: "NeoGeoCD".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/ngcd.png".to_string(), is_active: true },
        PlatformInfo { id: 57, name: "Fairchild Channel F".to_string(), slug: "ChannelF".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/chf.png".to_string(), is_active: true },
        PlatformInfo { id: 63, name: "Watara Supervision".to_string(), slug: "Supervision".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/wsv.png".to_string(), is_active: true },
        PlatformInfo { id: 69, name: "Mega Duck".to_string(), slug: "MegaDuck".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/duck.png".to_string(), is_active: true },
        PlatformInfo { id: 71, name: "Arduboy".to_string(), slug: "Arduboy".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/ard.png".to_string(), is_active: true },
        PlatformInfo { id: 72, name: "WASM-4".to_string(), slug: "WASM4".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/wasm4.png".to_string(), is_active: true },
        PlatformInfo { id: 73, name: "Arcadia 2001".to_string(), slug: "Arcadia2001".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/a2001.png".to_string(), is_active: true },
        PlatformInfo { id: 74, name: "Interton VC 4000".to_string(), slug: "VC4000".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/vc4000.png".to_string(), is_active: true },
        PlatformInfo { id: 76, name: "TurboGrafx-CD".to_string(), slug: "PCECD".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/pccd.png".to_string(), is_active: true },
        PlatformInfo { id: 77, name: "Atari Jaguar CD".to_string(), slug: "JaguarCD".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/jcd.png".to_string(), is_active: true },
        PlatformInfo { id: 78, name: "Nintendo DSi".to_string(), slug: "DSi".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/dsi.png".to_string(), is_active: true },
        PlatformInfo { id: 100, name: "PC (Linux)".to_string(), slug: "PC (Linux)".to_string(), icon_url: "assets/systems/linux.png".to_string(), is_active: false },
        PlatformInfo { id: 101, name: "PC (Windows)".to_string(), slug: "PC (Windows)".to_string(), icon_url: "assets/systems/windows.png".to_string(), is_active: false },
        PlatformInfo { id: 102, name: "Steam".to_string(), slug: "steam".to_string(), icon_url: "assets/systems/steam.png".to_string(), is_active: false },
        PlatformInfo { id: 103, name: "Heroic".to_string(), slug: "heroic".to_string(), icon_url: "assets/systems/heroic.png".to_string(), is_active: false },
        PlatformInfo { id: 104, name: "Lutris".to_string(), slug: "lutris".to_string(), icon_url: "assets/systems/lutris.png".to_string(), is_active: false },
        PlatformInfo { id: 105, name: "PlayStation 3".to_string(), slug: "PS3".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/ps3.png".to_string(), is_active: false },
        PlatformInfo { id: 106, name: "PlayStation 4".to_string(), slug: "PS4".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/ps4.png".to_string(), is_active: false },
        PlatformInfo { id: 107, name: "Nintendo 3DS".to_string(), slug: "3DS".to_string(), icon_url: "https://static.retroachievements.org/assets/images/system/3ds.png".to_string(), is_active: false },
    ]
}
